name: furniture_app
description: Furniture Management Application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP & Networking
  http: ^1.1.0
  dio: ^5.3.1

  # State Management
  provider: ^6.0.0

  # Local Storage
  shared_preferences: ^2.2.1

  # JSON
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

  # Date & Time
  intl: ^0.19.0

  # UI
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.2.0

  # Charts
  fl_chart: ^0.63.0

  # PDF & Printing
  pdf: ^3.10.4
  printing: ^5.11.0

  # Validators
  validators: ^3.0.0

  # Logging
  logger: ^2.0.1
  # Image picker for product images
  image_picker: ^0.8.7+4
  # For multipart content types
  http_parser: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
 # json_serializable: ^6.7.1

flutter:
  uses-material-design: true